theme: jekyll-theme-dinky
title: Introduction to Bash: Using the Terminal For Bioinformatics
description: <img src="https://uofabioinformaticshub.github.io/RAdelaide-July-2017/images/UoA_logo_col_vert.png" alt="UofAlogo" border="0px" style="width:143px;height:106px;"><br><br>Course Homepage<br>September 2017
